### ISSUE TITLE
Commits from the year prior are bleeding over into this year

### ISSUE THREAD

**Issue by plicjo** [dkarter/weekly_commits#3]
I'm posting this on August 31, 2020 at 9PM.

Sept 1 hasn't hit yet. There are commits showing on Tuesday from the year prior.

<img width="491" alt="Screen Shot 2020-08-31 at 8 48 22 PM" src="https://user-images.githubusercontent.com/7145362/91782589-8aee8f80-ebcb-11ea-9e7c-e29d29af6e3c.png">

**Comment by dkarter** [comment]
🤷🏻‍♂️ I don't know - maybe something is wrong with the git log query... I haven't used this utility in a few years and don't have much time to debug it. Happy to accept PRs though
